services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    #container_name: sqlserver2022
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA= Y
      - MSSQL_SA_PASSWORD= Admin@123
      - MSSQL_PID=Express
    volumes:
      - sqlserverdata:/var/opt/mssql
volumes:
  sqlserverdata:
    # Comandos útiles:
    # Levantar los contenedores en segundo plano:
    #   docker-compose up -d
    # Apagar y eliminar contenedores (no borra los volúmenes):
    #   docker-compose down
